FROM python:3.9

# File Author / Maintainer
LABEL org.opencontainers.image.authors="Luca Cozzuto <lucacozzuto@gmail.com>" 

#upgrade pip
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools wheel

RUN pip3 install numpy matplotlib scikit-learn scikit-image nexusformat 
RUN pip3 install pywavelets
